version: "3"

volumes:
  mssql_data:
    driver: local

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    volumes:
      - mssql_data:/var/opt/mssql
